#!/usr/bin/bash

# Permissions
sudo chmod 777 *
sudo chmod 777 * -R

echo ""

echo "---------------------------"
echo "Installing Requirements..."
echo "---------------------------"

echo ""

echo "Updating..."
sudo apt update -y && sudo apt upgrade -y

clear

echo "Making sure Python3 with PIP is installed..."
echo ""
sudo apt install python3 -y
sudo apt install python3-pip -y

clear

echo "Installing Modules..."
echo ""
sudo pip3 install -r core/requirements.txt

clear

echo "Installing Chrome browser..."
echo ""
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb -y
rm *.deb

clear

echo "Installing Chrome Driver..."
echo ""
sudo apt-get install unzip &&
a=$(uname -m) &&
wget -O /tmp/chromedriver/LATEST_RELEASE http://chromedriver.storage.googleapis.com/LATEST_RELEASE &&
if [ $a == i686 ]; then b=32; elif [ $a == x86_64 ]; then b=64; fi &&
latest=$(cat /tmp/chromedriver/LATEST_RELEASE) &&
wget 'http://chromedriver.storage.googleapis.com/'$latest'/chromedriver_linux'$b'.zip'
unzip chromedriver*.zip 
rm *.zip
chmod +x chromedriver
mv chromedriver core/
sudo ln -s ~/core/chromedriver /usr/bin/chromedriver

clear

echo "Installing Docker..."
echo ""
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
echo 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' |
sudo tee /etc/apt/sources.list.d/docker.list
sudo apt update -y
sudo apt remove docker docker-engine docker.io -y
sudo apt install docker-ce -y
sudo systemctl start docker
sudo Docker run hello-world
clear

echo "Downloading Anonsurf..."
echo ""
sudo git clone https://github.com/Und3rf10w/kali-anonsurf.git

clear

echo "Installing Anonsurf"
echo ""
cd kali-anonsurf
sudo bash installer.sh -y

echo "Installing Tor"
echo the installation will proceed automatically.
sudo apt install -y tor
sudo apt install -y netcat
sudo service tor start

# Permissions
sudo chmod 777 *
sudo chmod 777 * -R

clear

echo "All the requirements have been installed"
echo ""